name: branch-deploy

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v9.1.3
        with:
          trigger: ".deploy"
          noop_trigger: ".noop"
          #          reaction: "eyes"
          environment: "production"
          stable_branch: "main"
