name: branch-deploy

on:
  issue_comment:
    types: [created]
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: github/branch-deploy@v9.1.3
        with:
          trigger: ".deploy"
          noop_trigger: ".noop"
          #          reaction: "eyes"
          environment: "development"
          environment_urls: "development|https://pr-${{ github.event.number }}.matecki.website"
          stable_branch: "main"
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}
